credentials:
  github:
    PERSONAL_ACCESS_TOKEN: "[YOURS]"

  aws:
    ACCESS_KEY_ID: "[YOURS]"
    SECRET_ACCESS_KEY: "[YOURS]"

  mlflow_credentials:
    MLFLOW_TRACKING_URI: "[YOURS]"
    MLFLOW_TRACKING_USERNAME: "[YOURS]"
    MLFLOW_TRACKING_PASSWORD: "[YOURS]"

  dvc_config:
    DAGSHUB_REMOTE_URL: "[YOURS]"
    USERNAME: "[YOURS]"
    PASSWORD: "[YOURS]"
    
  metadata_path:
    METRICS_PATH: "./metrics"
    METRICS_FILE: "./metrics/metrics.json"
    MODEL_PATH: "./model"
